version: "3"

services: 

  base-ideac:
    image: base-ideac:latest
    build: 
      context: .
      dockerfile: base.ideac.dockerfile
      args: 
        USERNAME: ${USERNAME}
        UID: ${UID}
        GID: ${GID}
        IDEAC_MAJOR_VERSION: ${IDEAC_MAJOR_VERSION}
        IDEAC_MINOR_VERSION: ${IDEAC_MINOR_VERSION}
    hostname: base-ideac-1
    user: ${USERNAME}
    environment: 
      - DISPLAY=$DISPLAY
    network_mode: bridge
    volumes:
      - ~/.config/ideac-base-home:/home/${USERNAME}
      - ~/Documents:/home/${USERNAME}/Documents
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    command: /opt/ideac/bin/idea.sh