version: "3"
services:

  cpp-env-1:
    image: cpp-env:latest
    build:
      context: .
      dockerfile: cpp-Dockerfile
    container_name: cpp-env-1
    hostname: cpp-env-1
    user: vscode
    network_mode: bridge
    volumes:
      - ~/Documents:/home/vscode/Documents
      - ~/Documents/docker/vscode-servers/cpp:/home/vscode/.vscode-server

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    stdin_open: true
    tty: true

    command: /bin/bash
