version: "3"

services: 


  base-ideac:
    image: base-ideac:latest
    build: 
      context: .
      dockerfile: base.ideac.dockerfile
      args: 
        USERNAME: ${USERNAME}
        UID: ${UID}
        GID: ${GID}
        IDEAC_MAJOR_VERSION: ${IDEAC_MAJOR_VERSION}
        IDEAC_MINOR_VERSION: ${IDEAC_MINOR_VERSION}
    hostname: base-ideac-1
    user: ${USERNAME}
    environment: 
      - DISPLAY=$DISPLAY
    network_mode: bridge
    volumes:
      - ~/.config/ideac-base/.IdeaIC${IDEAC_MAJOR_VERSION}:/home/${USERNAME}/.IdeaIC${IDEAC_MAJOR_VERSION}
      - ~/.config/ideac-base/.java:/home/${USERNAME}/.java
      - ~/Documents:/home/${USERNAME}/Documents
      - ~/.gradle:/home/${USERNAME}/.gradle
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    command: /opt/ideac/bin/idea.sh


  java-ideac:
    image: java-ideac:latest
    build:
      context: .
      dockerfile: java.ideac.dockerfile
      args: 
        USERNAME: ${USERNAME}
    hostname: java-ideac-1
    user: ${USERNAME}
    environment:
      - DISPLAY=$DISPLAY
    network_mode: bridge
    volumes: 
      - ~/.config/ideac-java/.IdeaIC${IDEAC_MAJOR_VERSION}:/home/${USERNAME}/.IdeaIC${IDEAC_MAJOR_VERSION}
      - ~/.config/ideac-java/.java:/home/${USERNAME}/.java
      - ~/Documents:/home/${USERNAME}/Documents
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    command: /opt/ideac/bin/idea.sh


  rust-ideac:
    image: rust-ideac:latest
    build:
      context: .
      dockerfile: rust.ideac.dockerfile
      args: 
        USERNAME: $USERNAME
    hostname: rust-ideac-1
    user: $USERNAME
    environment: 
      DISPLAY: $DISPLAY
    network_mode: bridge
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.config/ideac-rust/.IdeaIC${IDEAC_MAJOR_VERSION}:/home/${USERNAME}/.IdeaIC${IDEAC_MAJOR_VERSION}
      - ~/.config/ideac-rust/.java:/home/${USERNAME}/.java
      - ~/.config/ideac-rust/.local/share/JetBrains:/home/${USERNAME}/.local/share/JetBrains
      - ~/Documents:/home/${USERNAME}/Documents
      - ~/Documents/docker/vscode-servers/rust:/home/${USERNAME}/.vscode-server
    cap_add: 
      - SYS_PTRACE
    security_opt: 
      - seccomp:unconfined
    stdin_open: true
    tty: true
    working_dir: /home/${USERNAME}
    command: /opt/ideac/bin/idea.sh
