version: "3"
services:

  rust-env-1:
    image: rust-env:latest
    container_name: rust-env-1
    hostname: rust-env-1
    user: vscode
    network_mode: bridge
    volumes:
      - ~/Documents:/home/vscode/Documents
      - ~/Documents/docker/vscode-servers/rust:/home/vscode/.vscode-server

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    stdin_open: true
    tty: true

    command: /bin/sh -c "while sleep 1000; do :; done"